global_costmap:
  robot_base_frame: thorvald_001/base_link
  update_frequency: 5.0
  static_map: true
  plugins:
    - {name: map_layer, type: "costmap_2d::StaticLayer"}
    - {name: global_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: global_inflation_layer, type: "costmap_2d::InflationLayer"}

